#!/usr/bin/env ruby

begin
  require 'hirb'
  Hirb.enable
rescue LoadError
end

def change_log(stream)
  ActiveRecord::Base.logger = Logger.new(stream)
  ActiveRecord::Base.clear_active_connections!
end

def show_log
  change_log(STDOUT)
end

def hide_log
  change_log(nil)
end

# showing log by default
IRB.conf[:IRB_RC] = Proc.new do 
  show_log
end