#!/bin/sh

export JAXERBASE=/Applications/Aptana_Jaxer
export ANCHOR=/Applications/Aptana_Jaxer

#default port
ManagerCmdPort=4328
## Get cmd line
while getopts 'p:' OPTION
do
  case $OPTION in
  p)  ManagerCmdPort="$OPTARG"
      ;;
  ?)  echo "Usage: $(basename $0) [-p managerCmdPort]" >&2
      exit 1
      ;;
  esac
done

shift $(($OPTIND - 1 ))
if [ $# -ge 1 ]; then
    echo "Usage: $(basename $0) [-p managerCmdPort]" >&2
    exit 2
fi

$JAXERBASE/jaxer/telljaxermanager -p $ManagerCmdPort stop
sleep 5
kill `cat /Users/max/dev/printio/printio/tmp/pids/jaxer.pid` > /dev/null 2>&1
rm /Users/max/dev/printio/printio/tmp/pids/jaxer.pid

export DYLD_LIBRARY_PATH=$JAXERBASE/Apache22/lib
$JAXERBASE/Apache22/bin/apachectl stop